[package]
name = "opencv-rust-example"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["mask-operations", "operation-with-images", "showing-image", "sobel-x-example"]

[workspace.dependencies]
opencv = "0.92.2"
